### ISSUE TITLE
Doesn't compile with Arduino 1.8.19/Digistump 1.6.7

### ISSUE THREAD

**Issue by froqstar** [g3gg0/DigiJoystick_FPV#2]
Hi, thanks a lot for sharing this! 

When trying to compile the CRSF example with Arduino 1.8.19/Digistump 1.6.7 I get the following error message:

```
Arduino: 1.8.19 (Linux), Board: "Digispark (Default - 16.5mhz)"

/home/froqstar/Arduino/libraries/DigiJoystick_FPV/examples/CRSF_Joystick/CRSF_Joystick.ino: In function 'void loop()':
CRSF_Joystick:270:38: error: invalid conversion from 'volatile uint8_t* {aka volatile unsigned char*}' to 'unsigned char*' [-fpermissive]
         usbSetInterrupt(&report[0], 8);
                                      ^
In file included from /home/froqstar/Arduino/libraries/DigiJoystick_FPV/DigiJoystick_FPV.h:23:0,
                 from /home/froqstar/Arduino/libraries/DigiJoystick_FPV/examples/CRSF_Joystick/CRSF_Joystick.ino:6:
/home/froqstar/Arduino/libraries/DigiJoystick_FPV/usbdrv.h:261:17: error:   initializing argument 1 of 'void usbSetInterrupt(unsigned char*, unsigned char)' [-fpermissive]
 USB_PUBLIC void usbSetInterrupt(uchar *data, uchar len);
                 ^
CRSF_Joystick:352:36: error: invalid conversion from 'volatile uint8_t* {aka volatile unsigned char*}' to 'unsigned char*' [-fpermissive]
       usbSetInterrupt(&report[0], 8);
                                    ^
In file included from /home/froqstar/Arduino/libraries/DigiJoystick_FPV/DigiJoystick_FPV.h:23:0,
                 from /home/froqstar/Arduino/libraries/DigiJoystick_FPV/examples/CRSF_Joystick/CRSF_Joystick.ino:6:
/home/froqstar/Arduino/libraries/DigiJoystick_FPV/usbdrv.h:261:17: error:   initializing argument 1 of 'void usbSetInterrupt(unsigned char*, unsigned char)' [-fpermissive]
 USB_PUBLIC void usbSetInterrupt(uchar *data, uchar len);
                 ^
CRSF_Joystick:361:38: error: invalid conversion from 'volatile uint8_t* {aka volatile unsigned char*}' to 'unsigned char*' [-fpermissive]
         usbSetInterrupt(&report[8], 8);
                                      ^
In file included from /home/froqstar/Arduino/libraries/DigiJoystick_FPV/DigiJoystick_FPV.h:23:0,
                 from /home/froqstar/Arduino/libraries/DigiJoystick_FPV/examples/CRSF_Joystick/CRSF_Joystick.ino:6:
/home/froqstar/Arduino/libraries/DigiJoystick_FPV/usbdrv.h:261:17: error:   initializing argument 1 of 'void usbSetInterrupt(unsigned char*, unsigned char)' [-fpermissive]
 USB_PUBLIC void usbSetInterrupt(uchar *data, uchar len);
                 ^
Using library DigiJoystick_FPV in folder: /home/froqstar/Arduino/libraries/DigiJoystick_FPV (legacy)
exit status 1
invalid conversion from 'volatile uint8_t* {aka volatile unsigned char*}' to 'unsigned char*' [-fpermissive]
```

Not sure whether I did everything correct, but it would be great if you could have a look at this, or alternatively post binaries of the latest code in your blogpost :) 

Thanks again and enjoy the great weather!

**Comment by Krovosys** [comment]
Hi @froqstar !

Did you somehow manage to solve this problem?

**Comment by froqstar** [comment]
@Krovosys nope :)

**Comment by Krovosys** [comment]
@g3gg0 I would be grateful if you could help us :)

**Comment by g3gg0** [comment]
hm for this case i always had an older version of arduino installed.
i think i did this with 1.6.5 or 1.6.12.
can you try with one of these?

**Comment by Krovosys** [comment]
Yes, I think I can try to do that.

**Comment by ValarMorguliss** [comment]
Hello, @g3gg0. I seem to have the same problem. But I'm afraid the problem is also because I'm not good at Arduino IDE. I'm afraid I'm doing something wrong. 

I just flashed with HEX file (which I downloaded from this site https://www.g3gg0.de/wordpress/arduino/attiny85-a-simple-crossfire-usb-adapter/) through the Digispark loader. And I had a problem with the stick freezes in my FPV simulator. I was hoping that another firmware would solve this problem.

Could you please provide the HEX file of your latest firmware for the Digispark loader? I would be very grateful to you.

**Comment by Krovosys** [comment]
I tried it on versions 1.6.5 - 1.6.12 - it's the same as the others :(

**Comment by BlutSuger** [comment]
Hi guys.

Has anyone been able to solve this problem? @g3gg0  @Krovosys @ValarMorguliss

**Comment by BlutSuger** [comment]
I would really like to build this dongle, and not to have problems with lags :)
